#!/usr/bin/env python3

import sys
import os

# Add the parent directory to sys.path to allow importing the package
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from klippy.klippy import main

if __name__ == "__main__":
    main()
